"""
Output writers for SpaceEngine catalog formats.

Produces:
  galaxies/desi_galaxies.csv   - bulk galaxies, CSV format
  galaxies/desi_qsos.sc        - QSO host objects (heavy/insane only)

Reference: SE galaxy CSV columns:
    Name, Type, RA, Dec, Dist, AbsMagn, Radius, Quat.w, Quat.x, Quat.y, Quat.z

We write all 11 columns to satisfy the format, but Quat is set to identity
(1,0,0,0) since stock SE catalogs almost universally omit orientation for
galaxies (M87's stock entry has a comment: "lol why does this exist for an
E0 galaxy?"). Random quats added visual variety with no scientific basis.

Coordinate conventions:
    RA  in decimal hours (DESI degrees / 15)
    Dec in decimal degrees
    Dist, Radius in parsecs

QSOs are emitted as Quasar blocks. In SpaceEngine they show up as
quasar objects (galaxies arrive as galaxy objects via the CSV), and SE
generates the central BHs procedurally. SPECTYPE='QSO' is also preserved
in the object name prefix ("DESI QSO ...").

History, so nobody "fixes" this again: an earlier revision emitted these
as Galaxy blocks, on the theory that the Quasar keyword was responsible
for oversized emission-region artifacts at high density (stock SE ships
only 13 Quasar-keyword objects, so large counts were untested territory).
That workaround was reverted. Quasar blocks are confirmed working in-game
at insane-tier density (~1.6M blocks). Do not switch the keyword without
re-testing in SE at full scale.

LogLevel 0 is set at the top of every SC file to suppress per-object
catalog-load warnings (a 300+ MB log on insane tier without it).
"""

import logging
import numpy as np
from pathlib import Path

log = logging.getLogger(__name__)

CSV_HEADER = "Name,Type,RA,Dec,Dist,AbsMagn,Radius,Quat.w,Quat.x,Quat.y,Quat.z"
SC_HEADER = "// Generated by desi-to-spaceengine\nLogLevel 0\n\n"


def _name_for_targetid(targetid, prefix='DESI'):
    """Build a stable display name from TARGETID."""
    return f"{prefix} {int(targetid)}"


def _format_float(val, fmt='.6g'):
    """NaN-safe float formatter that emits empty string for NaN/inf."""
    if val is None:
        return ''
    if isinstance(val, (int, np.integer)):
        return str(val)
    if not np.isfinite(val):
        return ''
    return format(val, fmt)


def write_galaxies_csv(path, names, types, ra_deg, dec_deg, dist_pc,
                       absmag, radius_pc):
    """
    Write the galaxy CSV. Quat fields are written as identity (1,0,0,0)
    since orientation isn't physically meaningful and stock SE galaxies
    typically omit it.
    """
    n = len(names)
    assert ra_deg.shape == (n,)
    assert dec_deg.shape == (n,)
    assert dist_pc.shape == (n,)
    assert absmag.shape == (n,)
    assert radius_pc.shape == (n,)

    ra_h = ra_deg / 15.0  # SE wants decimal hours

    path.parent.mkdir(parents=True, exist_ok=True)
    log.info(f"Writing {n:,} galaxies -> {path}")

    with path.open('w', encoding='ascii') as f:
        f.write(CSV_HEADER + '\n')
        for i in range(n):
            f.write(
                f"{names[i]},{types[i]},"
                f"{_format_float(ra_h[i], '.7f')},"
                f"{_format_float(dec_deg[i], '.7f')},"
                f"{_format_float(dist_pc[i], '.6g')},"
                f"{_format_float(absmag[i], '.4g')},"
                f"{_format_float(radius_pc[i], '.6g')},"
                f"1.0,0.0,0.0,0.0\n"
            )
    log.info(f"  wrote {path.stat().st_size:,} bytes")


def write_qsos_sc(path, names, types, ra_deg, dec_deg, dist_pc,
                  absmag, radius_pc):
    """
    Write QSO host objects as Quasar blocks (see module doc).
    Single .sc file, LogLevel 0 at top to suppress load warnings.
    """
    n = len(names)
    ra_h = ra_deg / 15.0
    path.parent.mkdir(parents=True, exist_ok=True)
    log.info(f"Writing {n:,} QSO hosts -> {path}")

    with path.open('w', encoding='ascii') as f:
        f.write(SC_HEADER)
        f.write("// DESI DR1 quasar hosts (SPECTYPE=='QSO' rows from iron/v1 zpix).\n")
        f.write("// Emitted as Quasar blocks; SE renders central BHs procedurally.\n\n")
        for i in range(n):
            f.write(f'Quasar "{names[i]}"\n{{\n')
            if types[i]:
                f.write(f'\tType "{types[i]}"\n')
            f.write(f'\tRA   {_format_float(ra_h[i], ".7f")}\n')
            f.write(f'\tDec  {_format_float(dec_deg[i], ".7f")}\n')
            f.write(f'\tDist {_format_float(dist_pc[i], ".6g")}\n')
            am = _format_float(absmag[i], '.4g')
            if am:
                f.write(f'\tAbsMagn {am}\n')
            r = _format_float(radius_pc[i], '.6g')
            if r:
                f.write(f'\tRadius {r}\n')
            f.write('}\n')
    log.info(f"  wrote {path.stat().st_size:,} bytes")
